### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by OKNoah** [stadt-bielefeld/merge-tiles#3]
```zsh
###################################################
## merge-tiles v1.0.3 #############################
###################################################
  Input directory: .
  Output directory: ./
  Workers: 2
  Formats: png
fs.js:143
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:632:3)
    at syncFileToBuffer (/Users/noah/.nvm/versions/v10.3.0/lib/node_modules/merge-tiles/node_modules/image-size/lib/index.js:83:6)
    at module.exports (/Users/noah/.nvm/versions/v10.3.0/lib/node_modules/merge-tiles/node_modules/image-size/lib/index.js:121:18)
    at scanInputData (/Users/noah/.nvm/versions/v10.3.0/lib/node_modules/merge-tiles/src/scanInputData.js:112:17)
    at merge (/Users/noah/.nvm/versions/v10.3.0/lib/node_modules/merge-tiles/src/merge.js:14:14)
    at Object.<anonymous> (/Users/noah/.nvm/versions/v10.3.0/lib/node_modules/merge-tiles/src/mergeCli.js:72:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
```

**Comment by geofreak** [comment]
Whats your cli command?
merge -i . -o ./ -f png -w 2

Did you run the command in the directory of the tiles?

x0_y0.pgw
x0_y0.png
...
...

**Comment by OKNoah** [comment]
@geofreak macOS. It's a problem with the `isImage` function from another package, which returns false for all the `bmp` files in my folder. That's as far as I got debugging.

I ended up doing `gm montage +frame +shadow +label -tile 14x350 -geometry 24x24+0+0 *.bmp combined.png` to combine them, worked perfect.
